server:
  port: 8989
spring:
  data:
    mongodb:
      # 如果有密码 uri: mongodb://name:pass@localhost:27017/test
      uri: mongodb://localhost:27017/test  # 多个用逗号分隔
    # 以下均为默认配置
    min-connection-per-host: 0
    max-connection-per-host: 100
    threads-allowed-to-block-for-connection-multiplier: 5
    server-selection-timeout: 30000
    max-wait-time: 120000
    max-connection-idle-time: 0
    max-connection-life-time: 0
    connect-timeout: 10000
    socket-timeout: 0
    socket-keep-alive: false
    ssl-enabled: false
    ssl-invalid-host-name-allowed: false
    always-use-m-beans: false
    heartbeat-socket-timeout: 20000
    heartbeat-connect-timeout: 20000
    min-heartbeat-frequency: 500
    heartbeat-frequency: 10000
    local-threshold: 15